### ISSUE TITLE
Conflict with Commodore 64 and VIC-20 cores/extensions

### ISSUE THREAD

**Issue by vonmillhausen** [goweiwen/Allium#46]
In `consoles.toml`, you currently have the following:

```toml
[[consoles]]
name = "Commodore 64"
cores = ["vice_x64"]
patterns = ["COMMODORE"]

[[consoles]]
name = "VIC-20"
cores = ["vice_xvic"]
patterns = ["VIC20"]
extensions = [
    "d64",
    "d6z",
    "d71",
    "d7z",
    "d80",
    "d81",
    "d82",
    "d8z",
    "g64",
    "g6z",
    "g41",
    "g4z",
    "x64",
    "x6z",
    "nib",
    "nbz",
    "d2m",
    "d4m",
    "t64",
    "tcrt",
    "prg",
    "p00",
    "crt",
    "cmd",
    "vfl",
    "vsf",
    "gz",
    "20",
    "40",
    "60",
    "a0",
    "b0",
]
```

However, as related hardware, the Commodore 64 and VIC-20 emulators share many of the same file extensions - for example `.d64` disk images can be loaded on both systems, `.prg` files can be loaded on both, etc.. With the current setup, having a `.d64` file in a `Roms` folder called `Commodore 64 (COMMODORE)` will load the file in the VIC-20 emulator, due to the extension-first-then-folder rule for choosing a core to load. This means it's basically impossible to load any C64 game in Allium.

I'd suggest changing the above to:

```toml
[[consoles]]
name = "Commodore 64"
cores = ["vice_x64"]
patterns = ["COMMODORE"]

[[consoles]]
name = "VIC-20"
cores = ["vice_xvic"]
patterns = ["VIC20"]
```

Ditch the extensions for these two entirely, and just let them rely entirely on folder naming.
